spring:
  application:
    name: social-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/social_network
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update


